### ISSUE TITLE
In typescript, the code cannot run normally,

### ISSUE THREAD

**Issue by okuc** [moment/momentjs.com#635]
My code is as follows:
```
import moment from 'moment';
console.log(moment.locale()); // en
console.log(moment.duration('23:59:59'));
console.log(moment([2020, 0, 29]).fromNow());
```
In moment2.24.0, it can run very well. But after upgrading to 2.25.0, the following error was reported:
```
ERROR in D:\project\src\index.ts
./src/index.ts
[tsl] ERROR in D:\project\src\index.ts(1,20)
      TS2307: Cannot find module 'moment'.
```
I tried many kinds of solutions, but none of them succeeded. How can I solve them? Thank you

**Comment by kduffie** [comment]
I had the same problem.  I had to revert to 2.24.0 to get compilation to work.

**Comment by marwahaha** [comment]
Thanks for opening this request.
Does it still work in 2.25.3 ?

**Comment by okuc** [comment]
I just tested it, it works fine under 2.25.3 version, great, thank you！
